spring:
  application:
    name: employee-register
  datasource:
    url: jdbc:postgresql://database-1.cnkuowaowsym.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: 012345678910
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: hcompanysafiap@gmail.com
    password: wrre xukr egsx npdu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
