name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: build
    runs-on: ubuntu-latest
    strategy:
      ### ver pro java
    steps:
    - uses: actions/checkout@v4
    - name: Use MAVEN
      uses: actions/setup-node@v3
    - run: ### run build java

    ### Terraform
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
    
    - name: Terraform Init
      id: init
      run: terraform init
    
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
